# Generated by Django 4.2.29 on 2026-03-07 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=4)),
                ('order_type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('executed_qty', models.CharField(blank=True, default='', max_length=30)),
                ('avg_price', models.CharField(blank=True, default='', max_length=30)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Order Record',
                'verbose_name_plural': 'Order Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
